#go-task generate
#NOTE: update event handlers 
version: "3"

tasks:
  generate_deals:
    aliases:
      - gen-deals
    desc: "Generate golang code from proto"
    cmds:
      - protoc -I proto proto/deal/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
  generate_distributor:
    aliases:
      - gen-dist
    desc: "Generate golang code from proto"
    cmds:
      - protoc -I proto proto/distributor/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
  generate_payment:
    aliases:
      - gen-payments
    desc: "Generate golang code from proto"
    cmds:
      - protoc -I proto proto/payment/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
  generate_ticket:
    aliases:
      - gen-tickets
    desc: "Generate golang code from proto"
    cmds:
      - protoc -I proto proto/ticket/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
  generate_event:
    aliases:
      - gen-events
    desc: "Generate golang code from proto"
    cmds:
      - protoc -I proto proto/event/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
  generate:
    aliases:
      - gen
    desc: "Generate golang code from proto"
    cmds: 
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative      
